### ISSUE TITLE
Exoplanet Detection Using ML and DL 

### ISSUE THREAD

**Issue by YB73** [The-Data-Alchemists-Manipal/MindWave#12]
Detecting exoplanets using Machine Learning and Deep Learning algorithms
Link to dataset : https://www.kaggle.com/datasets/keplersmachines/kepler-labelled-time-series-data

**Comment by YB73** [comment]
Would like to work on it under GSSOC'23

**Comment by s0oraj** [comment]
Hi @YB73  , iam a GSSOC23 contributer and I would like to resolve this issue

Can you assign me this issue? Or any other issues you might have?
Heres My Resume which you might find useful: [Resume](https://github.com/s0oraj/Animus/files/11521330/Resume.pdf)
Here is my background in ML:

1) 6 months plus experience in working under college professors for research project on medical image classification.
2) Got 228 global rank in Amazon ML Challenge 2023 out of 30000+ teams participating.
3) Experienced with trainig machine Learning Models. Including image preprocessing techniues such as histrogram equilization, augmentation, stationary wavelet transformation, image segmentation. Along with feature extraction from models like resnet50 inceptionv3 vgg16 etc

Looking forward to hear from you.

**Comment by ASHWIN492** [comment]
Hey @YB73  , I am a GSSOC contributor . I would like to work on this issue.

**Comment by khusheekapoor** [comment]
@YB73 you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

@s0oraj @ASHWIN492  - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue on similar lines.
