### ISSUE TITLE
Breast Cancer Prediction using ANN

### ISSUE THREAD

**Issue by YB73** [The-Data-Alchemists-Manipal/MindWave#15]
## 💥 Proposal

Predicting breast cancer, whether it is malignant or benign, using ANN
Dataset used : https://www.kaggle.com/datasets/yasserh/breast-cancer-dataset

**Comment by yashigit21** [comment]
Please assign me this issue under GSSOC'23

**Comment by yashigit21** [comment]
I'd like to work on this project.Please assign this issue under GSSOC'23.

**Comment by KEERTHI1912** [comment]
I'd like to work on this issue as I am already familiar with ANN and have worked with cancer predictions.

**Comment by s0oraj** [comment]
Hi @YB73  , iam a GSSOC23 contributer and I would like to resolve this issue

Can you assign me this issue? Or any other issues you might have?
Heres My Resume which you might find useful: [Resume](https://github.com/s0oraj/Animus/files/11521330/Resume.pdf)
Here is my background in ML:

1) 6 months plus experience in working under college professors for research project on medical image classification.
2) Got 228 global rank in Amazon ML Challenge 2023 out of 30000+ teams participating.
3) Experienced with trainig machine Learning Models. Including image preprocessing techniues such as histrogram equilization, augmentation, stationary wavelet transformation, image segmentation. Along with feature extraction from models like resnet50 inceptionv3 vgg16 etc

Looking forward to hear from you.

**Comment by nitin-pandita** [comment]
> ## 💥 Proposal
> Predicting breast cancer, whether it is malignant or benign, using ANN Dataset used : https://www.kaggle.com/datasets/yasserh/breast-cancer-dataset

Hey, @YB73 the project seems very interesting if you could assign this to me it would be just great. I have worked on ANN for a while and would like to take this issue. 

Looking forward for your message.

**Comment by ASHWIN492** [comment]
I'd like to work on this project. I am  GSSOC23 contributor

**Comment by khusheekapoor** [comment]
@YB73  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

@yashigit21 @KEERTHI1912 @s0oraj @nitin-pandita @ASHWIN492   - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue and use the same algorithm (ANN) on a different dataset.

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.
