### ISSUE TITLE
Search Bot which summarizes the result

### ISSUE THREAD

**Issue by mahesh-11102** [The-Data-Alchemists-Manipal/MindWave#30]
## Aim
To make a User Friendly search bot which summarizes the result requested by the user.

## What does this project do
- The search bot locates the relevant webpage and extracts the text content from it using the `Beautiful Soup library`.
- Using `Gensim Library` I've summarized the result.
- With an interface created using the `Tkinter GUI` toolkit that enables the user to easily enter their search query in the text box and initiate the search by clicking the submit button.
-  The search bot also allows users to create a word cloud visualization of the summary using the `WordCloud library`. This feature is particularly useful in visualizing the most prominent words in the summary and providing a quick overview of the main themes and ideas presented in the content.

<hr>

## Flow chart of the process
- Text summarization
![image](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/77436328/cf0f220d-af9a-4b0c-9421-28533a9bfdb9)
- Whole process
![image](https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/77436328/bac31a70-d940-4b39-8a5b-01fe48d81384)
<hr>

## Snapshot of the project

<p>
    <img src="https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/77436328/e9f4c359-2546-40be-9897-98d779b5484e" width="350" height="450">
   <img src="https://github.com/avinashkranjan/Amazing-Python-Scripts/assets/77436328/2a169568-9cf2-4dfd-ad2c-19b5c8d02533" width="350" height="450">
</p>

**Comment by lakshmi-n-i** [comment]
I have previously worked on tokenization and wordcloud and I'm very interested in working on this issue. Please assign it to me under GSSOC'23

**Comment by khusheekapoor** [comment]
@mahesh-11102   - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

@lakshmi-n-i  - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue and use the same algorithm (natural language processing) on a different dataset.
