### ISSUE TITLE
Hypertuned prediction model on diabetes dataset

### ISSUE THREAD

**Issue by lcs2022026** [The-Data-Alchemists-Manipal/MindWave#48]
@khusheekapoor
the dataset i will use is here-https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database
please assign this project to me
i am GSSOC'23 contributor

**Comment by lcs2022026** [comment]
@khusheekapoor
the dataset i will use is here-https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database
please assign this project to me
i am GSSOC'23 contributor
@khusheekapoor

**Comment by tushtithakur** [comment]
Hi, I'm excited about the MindWave project for beginners to learn data science and ML algorithms. With my experience in Python and ML algorithms, I'd love to contribute to and enhance MindWave.
I would be grateful if you could assign this project to me. Looking forward to collaborate.

**Comment by tushtithakur** [comment]
Hi, I'm thrilled about the MindWave project for beginners to learn data science and ML algorithms. With my experience in Python and ML, I'd love to contribute by enhancing MindWave with a hypertuned prediction model on the diabetes dataset. Please consider assigning me this task. Excited to collaborate and make MindWave even better!

**Comment by khusheekapoor** [comment]
@lcs2022026 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

@tushtithakur  - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue on the similar lines.
