### ISSUE TITLE
Spotify : Music Recommendor System

### ISSUE THREAD

**Issue by samarthjain422005** [The-Data-Alchemists-Manipal/MindWave#50]
## 💥 Proposal

I would ike to work on spotify/YT music music recommendor system , which would recommend the correct choice of songs to the users according to their previous watch lists and genre.

**Comment by khusheekapoor** [comment]
@samarthjain422005 - which algorithms will you be using?

**Comment by samarthjain422005** [comment]
i woud be using kaggle to collet the dataset  will preprocess it using python modules , create tf-idf features of the artists genres , then connect it with spotify api , creating a playlist vector and generate recommendations using sklearn and matplotlib

**Comment by nk-droid** [comment]
I would like to work on this project.

**Comment by khusheekapoor** [comment]
@samarthjain422005 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

@nk-droid  - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue on the similar lines.

**Comment by samarthjain422005** [comment]
@khusheekapoor i am having trouble with the repo setup , can you please help me out with it?

**Comment by samarthjain422005** [comment]
@khusheekapoor 

> @khusheekapoor i am having trouble with the repo setup , can you please help me out with it?

**Comment by samarthjain422005** [comment]
hi , i have created a pull request , please allow the same.
