### ISSUE TITLE
CNN models on HAR Dataset

### ISSUE THREAD

**Issue by hkcs1206** [The-Data-Alchemists-Manipal/MindWave#52]
## 💥 Proposal
I am a GSSOC'23 Contributor
I am willing to implement different CNN models on Human Activity Recognition(HAR) dataset.
Dataset Link - https://www.kaggle.com/datasets/meetnagadia/human-action-recognition-har-dataset
So, Kindly assign it to me.

**Comment by tushtithakur** [comment]
Hi, I am very much interested and would like to contribute as a part of @GSSOC'23. 
Please assign the task to me. Thank you.

**Comment by Krishna9027** [comment]
### **_PROPOSAL_**


I would like to make this CNN model on HR dataset that will classify human activities by training and testing the model by the HR dataset using some unsupervised leaning algorithms.



I would ask you to assign me this project so that I can start working as soon as possible

In anticipation of your reply .

**Comment by khusheekapoor** [comment]
@hkcs1206  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

@tushtithakur @Krishna9027   - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue on the similar lines.

**Comment by hkcs1206** [comment]
Hey, when I am trying to push my code. I am getting this error,
remote: Permission to The-Data-Alchemists-Manipal/MindWave.git denied to hkcs1206.
fatal: unable to access 'https://github.com/The-Data-Alchemists-Manipal/MindWave.git/': The requested URL returned error: 403
What  I should do?
