### ISSUE TITLE
add contributors graph 

### ISSUE THREAD

**Issue by S-ishita** [The-Data-Alchemists-Manipal/MindWave#56]
## 💥 Proposal

I want to add conributors graph in readme.Please assign this issue to me under  GSSOC

**Comment by tushtithakur** [comment]
Hi, I am very much interested and would like to contribute as a part of @GSSOC'23.
Please assign the task to me. Thank you.

**Comment by khusheekapoor** [comment]
@S-ishita - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

@tushtithakur - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue and use the same algorithm (ANN) on a different dataset.

**Comment by S-ishita** [comment]
@khusheekapoor i wont be using ml dataset.

**Comment by khusheekapoor** [comment]
@S-ishita - sorry for the confusion!

**Comment by S-ishita** [comment]
@khusheekapoor someone already updated it
