### ISSUE TITLE
Fake News Prediction using Logistic Regression

### ISSUE THREAD

**Issue by Mansi168** [The-Data-Alchemists-Manipal/MindWave#59]
I would like to work on this project where i will be building a Fake News Prediction System using Machine Learning with Python. I will be using Logistic Regression model for prediction.

@khusheekapoor Please assign this issue to me

**Comment by tushtithakur** [comment]
Hi, I am very much interested and would like to contribute as a part of @GSSOC'23.
Please assign the task to me. Thank you.

**Comment by ritikalath30** [comment]
I am a GSSCOC contributor and I wish to work on this project.

**Comment by preetimahto17** [comment]
Hello! I'm really excited about this fake news detection project. I would love to contribute and work on it. Could you kindly assign the project to me? I'm confident that I can make a valuable contribution and help enhance the model's accuracy and reliability. Thank you in advance!

**Comment by khusheekapoor** [comment]
@Mansi168  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

@ritikalath30 @preetimahto17 @tushtithakur - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue on the similar lines.

**Comment by Mansi168** [comment]
okay thanks @khusheekapoor :)

**Comment by Mansi168** [comment]
okay thanks @khusheekapoor :)
