### ISSUE TITLE
Malaria diseases detection using deep learning

### ISSUE THREAD

**Issue by Mansi168** [The-Data-Alchemists-Manipal/MindWave#60]
hey @khusheekapoor i would like to work on this project...please assign this to me :)

**Comment by tushtithakur** [comment]
Hi, I am very much interested and would like to contribute as a part of @GSSOC'23.
Please assign the task to me. Thank you.

**Comment by khusheekapoor** [comment]
@Mansi168 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

@tushtithakur  - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue on the similar lines.

**Comment by Mansi168** [comment]
Thanks @khusheekapoor :)

**Comment by Mansi168** [comment]
hey @khusheekapoor u have labelled it wrong it is a deep learning project not machine learning. kindly change it. thanks :)
