### ISSUE TITLE
Document classification using DL

### ISSUE THREAD

**Issue by nk-droid** [The-Data-Alchemists-Manipal/MindWave#62]
I would like to add a document classification model. The model will predict if an image is of Aadhaar Card, Pan Card, Driving License, Passport or Voter ID.

**Comment by tushtithakur** [comment]
Hi, I am very much interested and would like to contribute as a part of @GSSOC'23.
Please assign the task to me. Thank you.

**Comment by khusheekapoor** [comment]
@nk-droid - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

@tushtithakur - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue on the similar lines.
