### ISSUE TITLE
Parkinson's Disease Prediction Model Using Machine Learning

### ISSUE THREAD

**Issue by tushtithakur** [The-Data-Alchemists-Manipal/MindWave#63]
## 💥 Proposal

This model is designed to build a system that can predict whether a person has Parkinson's disease or not with the help of Machine Learning. I will use Support Vector Machine(SVM) model for the prediction. I would like to contribute to this project as a part of @GSSOC'23.
Please assign the task to me. Thank you.

**Comment by ritikalath30** [comment]
In order to identify the early onset of Parkinson's disease it is necessary to build a model with excellent accuracy hence to achieve this I will be using the XGBoost algorithm. 
Being a GSSOC contributor I wish to contribute to this project.
Could you assign it to me

**Comment by tushtithakur** [comment]
> In order to identify the early onset of Parkinson's disease it is necessary to build a model with excellent accuracy hence to achieve this I will be using the XGBoost algorithm. Being a GSSOC contributor I wish to contribute to this project. Could you assign it to me

Hi Ritika,
I have raised the issue for myself for GSSOC 23'. Kindly raise an issue for yourself related to another topic or Issue. Thank You

**Comment by khusheekapoor** [comment]
@tushtithakur - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

@ritikalath30 - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue with the different model that you will be using.

**Comment by tushtithakur** [comment]
Thanks @khusheekapoor

**Comment by tushtithakur** [comment]
Hi @khusheekapoor
I have opened a pull request.
Kindly merge if everything is fine with my project and give me the GSSOC'23 tag
Thank you.
