### ISSUE TITLE
Dermatology Disease Classification by SVM, Random Forest, Logistic and finding the best model

### ISSUE THREAD

**Issue by lcs2022026** [The-Data-Alchemists-Manipal/MindWave#66]
@khusheekapoor 
I am GSSOC'23 contributor
I want to do this project 
I will be using this dataset:- https://www.kaggle.com/datasets/olcaybolat1/dermatology-dataset-classification

**Comment by lcs2022026** [comment]
@khusheekapoor
I am GSSOC'23 contributor
I want to do this project
I will be using this dataset:- https://www.kaggle.com/datasets/olcaybolat1/dermatology-dataset-classification
@khusheekapoor

**Comment by Jyotsna1304** [comment]
Hello, 
I'm a GSSoC'23 contributor. Can you please assign me this issue. I'll do the disease classification using the above mentioned model and come up with the best model.

**Comment by khusheekapoor** [comment]
@lcs2022026 -  you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

@Jyotsna1304 - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue on the similar lines.
