### ISSUE TITLE
Heart Disease prediction using Logistic Regression

### ISSUE THREAD

**Issue by itsdebartha** [The-Data-Alchemists-Manipal/MindWave#93]
## 💥 Proposal

I am Debartha Paul, a GSSoC'23 contributor. I propose to implement the logistic regression methods to predict heart disease using The R Programming Language. The dataset is available at https://www.kaggle.com/datasets/johnsmith88/heart-disease-dataset

#### Steps:

- Load and clean data, handle missing observations
- Apply the logistic regression methods to fit a model
- Predict values and measure accuracy
- Document each and every instance of the work

#### Tools:
- Generalised Linear Models
- ROC

(A clear and concise description of what the proposal is.)

**Comment by Shivangi-06** [comment]
Can U please assign me the issue

**Comment by khusheekapoor** [comment]
@itsdebartha  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset_language.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset - language`.

@Shivangi-06   - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue and use the same algorithm (ANN) on a different dataset.
